//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeThuoc.Thuoc_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacSi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BacSi()
        {
            this.DonThuoc = new HashSet<DonThuoc>();
        }
    
        public string MaBacSi { get; set; }
        public string TenBacSi { get; set; }
        public string MatKhau { get; set; }
        public string MaKhoa { get; set; }
        public string MaChucVu { get; set; }
        public bool GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string Sdt { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public System.DateTime NgayBatDauLam { get; set; }
        public int PhanQuyen { get; set; }
        public string Email { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual Khoa Khoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonThuoc> DonThuoc { get; set; }
    }
}
