//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeThuoc.Thuoc_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonThuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonThuoc()
        {
            this.DonVaThuoc = new HashSet<DonVaThuoc>();
        }
    
        public string MaDon { get; set; }
        public string MaBacSi { get; set; }
        public string MaBenhNhan { get; set; }
        public string BenhLi { get; set; }
        public bool BaoHiem { get; set; }
        public System.DateTime NgayLamDon { get; set; }
        public System.DateTime NgayTaiKham { get; set; }
    
        public virtual BacSi BacSi { get; set; }
        public virtual BenhNhan BenhNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonVaThuoc> DonVaThuoc { get; set; }
    }
}
