//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeThuoc.Thuoc_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THUOC()
        {
            this.DonVaThuoc = new HashSet<DonVaThuoc>();
        }
    
        public string MaThuoc { get; set; }
        public string TenThuoc { get; set; }
        public string DangThuoc { get; set; }
        public string CongDung { get; set; }
        public string TacDungPhu { get; set; }
        public string MaLoai { get; set; }
        public string SoLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonVaThuoc> DonVaThuoc { get; set; }
        public virtual LoaiThuoc LoaiThuoc { get; set; }
    }
}
